### ISSUE TITLE
TypeError: could not convert value for property `action' from tuple to GtkFileChooserAction

### ISSUE THREAD

**Issue by livibetter** [paul-nechifor/space-hoarder#1]
I am using 15be64f2ac95c342ed6b006a209191b92f293606 and GTK+ 3.14.13 with pygobject 3.14.0, I got the following error when click on Open button:

``` python
Traceback (most recent call last):
  File "./space-hoarder.py", line 78, in onOpenClicked
    dialog = Gtk.FileChooserDialog("Pick a directory", self, action, opts)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 175, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 537, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 175, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 175, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: could not convert value for property `action' from tuple to GtkFileChooserAction
```

I removed the comma in line 73:

``` python
        action = Gtk.FileChooserAction.SELECT_FOLDER,
```

The error went away.

**Comment by paul-nechifor** [comment]
Thanks very much for this bug report! This looks like a common problem I get when I refactor Python code, I forget to remove commas. :)

I usually use the program from the command line and haven't noticed the Open button doesn't work. D'oh!
